server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
        # ?? ??? ??? ???? ??? ? ??. Resource Server ?? ?? ????? ??.
          issuer-uri: http://localhost:8883/auth/realms/baeldung
        # ??? ???? ???? ?? ???? ??? URI
          jwk-set-url: http://localhost:8083/auth/realms/baeldung/protocol/openid-connect/certs